In [8]:
import torch.nn as nn  # type: ignore
import torch # type: ignore
import math
class Softmax(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        return torch.exp(x) / sum(torch.exp(x))

class softmax_stable(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        c = max(x)
        return torch.exp(x - c) / sum(torch.exp(x - c))
        

In [10]:
data = torch.Tensor([1, 2, 3])
softmax = Softmax()
output = softmax(data)
print(output)
data = torch.Tensor([1, 2, 3])
softmax = softmax_stable()
output = softmax(data)
print(output)

tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])


In [75]:
class Person(): 
    def __init__(self, name, yob):
        self.name = name
        self.yob = yob

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.grade = grade
    def describe(self):
        print(f"Student - Name: {self.name} - YoB: {self.yob} - Grade: {self.grade}")

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.subject = subject
    def describe(self):
        print(f"Teacher - Name: {self.name} - YoB: {self.yob} - Subject: {self.subject}")

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self.specialist = specialist
    def describe(self):
        print(f"Doctor - Name: {self.name} - YoB: {self.yob} - Specialist: {self.specialist}")

class Ward():
    def __init__(self, name):
        self.name = name
        self.lst_people = []

    def describe(self):
        print(f"Ward Name: {self.name}")
        [i.describe() for i in self.lst_people]

    def add_person(self, person):
        self.lst_people.append(person)

    def count_doctor(self):
        return sum([1 for i in self.lst_people if isinstance(i, Doctor)])

    def sort_age(self):
        self.lst_people = sorted(self.lst_people, key=lambda x: x.yob, reverse=True)

    def compute_average(self):
        teachers_yob = [i.yob for i in self.lst_people if isinstance(i, Teacher)]
        return sum(teachers_yob) / len(teachers_yob)

In [76]:
student1 = Student ( name ="studentA", yob =2010 , grade ="7")
student1 . describe ()

Student - Name: studentA - YoB: 2010 - Grade: 7


In [77]:
teacher1 = Teacher ( name ="teacherA", yob =1969 , subject ="Math")
teacher1 . describe ()

Teacher - Name: teacherA - YoB: 1969 - Subject: Math


In [78]:
doctor1 = Doctor ( name ="doctorA", yob =1945 , specialist ="Endocrinologists")
doctor1 . describe ()

Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists


In [79]:
teacher2 = Teacher ( name ="teacherB", yob =1995 , subject ="History")
doctor2 = Doctor ( name ="doctorB", yob =1975 , specialist ="Cardiologists")
ward1 = Ward ( name ="Ward1")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
ward1 . describe ()

Ward Name: Ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists


In [80]:
print ( f"\nNumber of doctors : { ward1 . count_doctor ()}")


Number of doctors : 2


In [81]:
print ("\nAfter sorting Age of Ward1 people ")
ward1 . sort_age ()
ward1 . describe ()


After sorting Age of Ward1 people 
Ward Name: Ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists


In [82]:
print ( f"\nAverage year of birth ( teachers ): { ward1 . compute_average ()}")


Average year of birth ( teachers ): 1982.0


In [87]:
class MyStack():
    def __init__(self, capacity):
        self.capacity = capacity
        self.items = []

    def is_empty(self):
        return len(self.items) == 0

    def is_full(self):
        return len(self.items) == self.capacity

    def pop(self):
        return self.items.pop()

    def push(self, value):
        self.items.append(value)

    def top(self):
        return self.items[-1]

In [88]:
stack1 = MyStack ( capacity =5)
stack1 . push (1)
stack1 . push (2)
print ( stack1 . is_full () )
print ( stack1 . top () )
print ( stack1 . pop () )
print ( stack1 . top () )
print ( stack1 . pop () )
print ( stack1 . is_empty () )

False
2
2
1
1
True


In [97]:
class MyQueue():
    def __init__(self, capacity):
        self.capacity = capacity 
        self.items = []

    def is_empty(self):
        return len(self.items) == 0

    def is_full(self):
        return len(self.items) == self.capacity

    def dequeue(self):
        return self.items.pop(0)

    def enqueue(self, value):
        self.items.append(value)

    def front(self):
        return self.items[0]

In [98]:
queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
queue1 . enqueue (2)
print ( queue1 . is_full () )
print ( queue1 . front () )
print ( queue1 . dequeue () )
print ( queue1 . front () )
print ( queue1 . dequeue () )
print ( queue1 . is_empty () )

False
1
1
2
2
True


In [99]:
import torch # type: ignore
import torch . nn as nn # type: ignore

data = torch . Tensor ([1 , 2 , 3])
softmax_function = nn . Softmax ( dim =0)
output = softmax_function ( data )
assert nn.isclose(round ( output [0]. item () , 2), 0.09, rtol=1e-09, atol=1e-09)
output

tensor([0.0900, 0.2447, 0.6652])

In [101]:
import torch # type: ignore
import torch . nn as nn # type: ignore

class MySoftmax ( nn . Module ) :
    def __init__ ( self ) :
        super () . __init__ ()
    def forward ( self , x ):
        return torch.exp(x) / sum(torch.exp(x))

data = torch . Tensor ([5 , 2 , 4])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert nn.isclose(round ( output [ -1]. item () , 2), 0.26, rtol=1e-09, atol=1e-09)
output

tensor([0.7054, 0.0351, 0.2595])

In [103]:
import torch # type: ignore
import torch . nn as nn # type: ignore
class MySoftmax ( nn . Module ) :
    def __init__ ( self ) :
        super () . __init__ ()
    def forward ( self , x ) :
        c = max(x)
        return torch.exp(x - c) / sum(torch.exp(x - c))

data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert nn.isclose(round ( output [0]. item () , 2), 0.0, rtol=1e-09, atol=1e-09)
output

tensor([0., 0., 1.])

In [104]:
import torch # type: ignore
import torch . nn as nn # type: ignore
class SoftmaxStable ( nn . Module ):
    def __init__ ( self ) :
        super () . __init__ ()
    def forward ( self , x ) :
        x_max = torch .max(x , dim =0 , keepdims = True )
        x_exp = torch . exp ( x - x_max . values )
        partition = x_exp .sum (0 , keepdims = True )
        return x_exp / partition
data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert nn.isclose(round ( output [ -1]. item () , 2), 0.67, rtol=1e-09, atol=1e-09)
output

tensor([0.0900, 0.2447, 0.6652])

In [110]:
from abc import ABC, abstractmethod
class Person(ABC): 
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob
    @abstractmethod
    def describe(self): pass

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self._grade = grade
    def describe(self):
        print(f"Student - Name: {self._name} - YoB: {self._yob} - Grade: {self._grade}")


In [111]:
student1 = Student ( name ="studentZ2023", yob =2011 , grade ="6")
assert student1 . _yob == 2011
student1 . describe ()

Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


In [112]:
class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self._subject = subject
    def describe(self):
        print(f"Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self._subject}")

In [113]:
teacher1 = Teacher ( name =" teacherZ2023 ", yob =1991 , subject =" History ")
assert teacher1 . _yob == 1991
teacher1 . describe ()

Teacher - Name:  teacherZ2023  - YoB: 1991 - Subject:  History 


In [114]:
class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self._specialist = specialist
    def describe(self):
        print(f"Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self._specialist}")

In [115]:
doctor1 = Doctor ( name =" doctorZ2023 ", yob =1981 , specialist =" Endocrinologists ")
assert doctor1 . _yob == 1981
doctor1 . describe ()

Doctor - Name:  doctorZ2023  - YoB: 1981 - Specialist:  Endocrinologists 


In [118]:
class Ward:
    def __init__(self, name):
        self.__name = name
        self.__lst_people = []

    def describe(self):
        print(f"Ward Name: {self.__name}")
        [i.describe() for i in self.__lst_people]

    def add_person(self, person):
        self.__lst_people.append(person)

    def count_doctor(self):
        return sum([1 for i in self.__lst_people if isinstance(i, Doctor)])

In [120]:
student1 = Student ( name ="studentA", yob =2010 , grade ="7")
teacher1 = Teacher ( name ="teacherA", yob =1969 , subject ="Math")
teacher2 = Teacher ( name ="teacherB", yob =1995 , subject ="History")
doctor1 = Doctor ( name ="doctorA", yob =1945 , specialist ="Endocrinologists")
doctor2 = Doctor ( name ="doctorB", yob =1975 , specialist ="Cardiologists")
ward1 = Ward ( name ="Ward1")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
assert ward1 . count_doctor () == 1
ward1 . add_person ( doctor2 )
ward1 . count_doctor ()

2

In [121]:
class MyStack():
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__items = []

    def is_empty(self):
        return len(self.__items) == 0

    def is_full(self):
        return len(self.__items) == self.__capacity

    def pop(self):
        return self.__items.pop()

    def push(self, value):
        self.__items.append(value)

    def top(self):
        return self.__items[-1]

In [122]:
stack1 = MyStack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . is_full () )


False


In [123]:
stack1 = MyStack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . top () )

2


In [124]:
class MyQueue():
    def __init__(self, capacity):
        self.__capacity = capacity 
        self.__items = []

    def is_empty(self):
        return len(self.__items) == 0

    def is_full(self):
        return len(self.__items) == self.__capacity

    def dequeue(self):
        return self.__items.pop(0)

    def enqueue(self, value):
        self.__items.append(value)

    def front(self):
        return self.__items[0]

In [125]:
queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . is_full () )

False


In [126]:
queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . front () )


1
